[tool.poetry]
name = "guts-2019-mstanks"
version = "0.1.0"
description = ""
authors = ["Luna <github@luna.allan.scot>"]

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
